package tn.esprit.b2.esprit1718b2businessbuilder.entities;
// Generated 25 fevr. 2015 16:41:06 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"

)
public class Category  implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id @GeneratedValue(strategy=IDENTITY)
     private Integer idCategory;
     private String name;
     private String description;
     private String status;
  

    public Category() {
    }

	
    public Category(String name, String status) {
        this.name = name;
        this.status = status;
    }
    public Category(String name, String description, String status) {
       this.name = name;
       this.description = description;
       this.status = status;

    }
   

    public Integer getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }

    

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }



    @Override
    public String toString() {
       
        return this.name ;
        //+" "+this.description+" "+this.status
    }




}


