package tn.esprit.b2.esprit1718b2businessbuilder.entities;
// Generated 25 fevr. 2015 16:41:06 by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name="comment"
)
public class Comment  implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id @GeneratedValue(strategy=IDENTITY)
     private Integer idComment;
    @ManyToOne
     private User user;
    @ManyToOne
     private FilDiscussion filDiscussion;
     private String contents;
    @Temporal(TemporalType.TIMESTAMP)
     private Date dateComment;
     private String status;

    public Comment() {
    }

    public Comment(User user, FilDiscussion filDiscussion, String contents, Date dateComment, String status) {
       this.user = user;
       this.filDiscussion = filDiscussion;
       this.contents = contents;
       this.dateComment = dateComment;
       this.status = status;
    }
   

    public Integer getIdComment() {
        return this.idComment;
    }
    
    public void setIdComment(Integer idComment) {
        this.idComment = idComment;
    }


    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }


    public FilDiscussion getFilDiscussion() {
        return this.filDiscussion;
    }
    
    public void setFilDiscussion(FilDiscussion filDiscussion) {
        this.filDiscussion = filDiscussion;
    }

    

    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }


    public Date getDateComment() {
        return this.dateComment;
    }
    
    public void setDateComment(Date dateComment) {
        this.dateComment = dateComment;
    }

    

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "{[id:"+this.idComment+"],[contents:"+this.contents+"],[Date:"+this.dateComment+"],[status:"+this.status+"]}"; //To change body of generated methods, choose Tools | Templates.
    }




}


